"\xEF\xBB\xBFroot": .
nr_predict_sld:
  file:
    nr_train: data/curves/np_out_REFL_194455_combined_data_auto.npy
    sld_train: data/curves/y_train_5_layers.npy
    experimental_nr_file: data/curves/expt/np_out_REFL_194438_combined_data_auto.npy
  models:
    model: data/pretrained/trained_model.pth
    normalization_stats: data/pretrained/normalization_stat.npy
    num_film_layers: 5
    num_curves: 1000
    epochs: 20
    batch_size: 64
    layers: 6
    dropout: 0.0873
sld_predict_chi:
  file:
    model_experimental_sld_profile: data/mod_expt.npy
    model_sld_file: data/mod_sld_fp49.npy
    model_chi_params_file: data/mod_params_fp49.npy
  models:
    latent_dim: 2
    batch_size: 16
    ae_epochs: 20
    mlp_epochs: 20
